security:
    # Utilise l'encodeur de mot de passe approprié
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définir le fournisseur d'utilisateur pour la connexion
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configurer les firewalls pour activer la sécurité
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_security_login
                check_path: app_security_login
                form_login:
    form_login:
    login_path: app_security_login
    check_path: app_security_login
    default_target_path: app_liste_rv_inde

            logout:
                path: app_security_logout
                target: app_security_login

    # Configurer les contrôles d'accès
    access_control:
        - { path: ^/security/login, roles: PUBLIC_ACCESS }
        - { path: ^/security/logout, roles: PUBLIC_ACCESS }
        - { path: ^/patient, roles: ROLE_USER }
